services:
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/development/docker/ssl-local-generator/certs:/etc/ssl/private
      - ~/development/php:/var/www
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/scripts:/scripts
    depends_on:
      - php
    command: ["sh", "-c", "/scripts/setup-vhost.sh && nginx -g 'daemon off;'"]

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: edhgt/laravel-ldap:${PHP_VERSION}
    volumes:
      - ~/development/php:/var/www
    depends_on:
      - db        

  db:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - db-data:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
        
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: edhgt/node:${NODE_VERSION}
    volumes:
      - ~/development:/var/www
      - ~/development/docker/ssl-local-generator/certs:/home/node/certs
    ports:
      - 5173:5173

volumes:
  db-data:
    external: true
    name: mariadb
