services:
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ~/development/docker/ssl-local-generator/certs:/etc/ssl/private
      - /home/edhernandez/development/projects/php:/var/www
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/scripts:/scripts
    command: ["sh", "-c", "/scripts/setup-vhost.sh && nginx -g 'daemon off;'"]

  php:
    container_name: php
    hostname: php
    build:
      context: ./php
      #dockerfile: Dockerfile.ldap
      #dockerfile: Dockerfile.ldap.sqlsrv.ftp.dev
      #dockerfile: Dockerfile.ldap.ftp
      #dockerfile: Dockerfile-fpm-8.2-ghostscript.production
      dockerfile: Dockerfile.ldap.sqlsrv.ftp.dev
      args:
        - PHP_VERSION=${PHP_VERSION}
    #image: edhgt/php:${PHP_VERSION}-laravel-ldap
    image: edhgt/php:${PHP_IMAGE_NAME}
    volumes:
      - ~/development/projects/php:/var/www
    environment:
      - TZ=America/Guatemala

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - db-data:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
        
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: edhgt/node:${NODE_VERSION}
    volumes:
      - ~/development/projects:/var/www
      # - ~/development/docker/ssl-local-generator/certs:/home/node/certs
    ports:
      - 5173:5173
      - 3000:3000
      - 3001:3001
      - 5001:5001

volumes:
  db-data:
    name: mariadb
    external: true
