ARG PHP_VERSION="8.4-fpm"
FROM php:${PHP_VERSION}

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    gnupg2 \
    curl \
    unzip \
    libxml2-dev \
    libpng-dev \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    unixodbc-dev \
    ca-certificates \
    apt-transport-https \
    libldap2-dev \
    ldap-utils \
    libssl-dev \
    && docker-php-ext-configure zip \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-configure ftp \
    && docker-php-ext-install \
        soap \
        mbstring \
        pdo \
        pdo_mysql \
        mysqli \
        xml \
        zip \
        ldap \
        gd \
        bcmath \
        exif \
        intl \
        ftp

# Instalar driver ODBC de Microsoft
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
       > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 \
    && pecl install pdo_sqlsrv sqlsrv \
    && docker-php-ext-enable pdo_sqlsrv sqlsrv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www
USER 1000
